### ISSUE TITLE
如何在FragmentStatePagerAdapter中使用

### ISSUE THREAD

**Issue by KagurazakaHanabi** [xujiaji/XMVP#1]
getItem返回的是android.support.v4.app.Fragment
而XBaseFragment继承android.app.Fragment
二者不通用啊...

**Comment by xujiaji** [comment]
这确实是个尴尬的问题，目前我的解决方式是是用v13包中的fragmentpageradapter，它可以用。我准备在下一个版本增加一个v4包的。

**Comment by KagurazakaHanabi** [comment]
好的,多谢!

**Comment by xujiaji** [comment]
已更新版本扩展v4包
